### ISSUE TITLE
Structural damping in OpenFAST model

### ISSUE THREAD

**Issue by RRiva** [IEAWindTask37/IEA-10.0-198-RWT#13]
The structural damping in the OpenFAST and HAWC2 model differ. The blade-only structural stability analysis of HAWCStab2 2.15 provides

Mode  |  % Critical damping  |  % Log decrement
------- | ---------------------- | --------------------
1st flap   |  0.3252 |  2.0434
1st edge  | 0.3614 | 2.2707
2nd flap  | 0.8304 | 5.2175

Although this damping has not been tuned accurately, these values should be realistic.

In the OpenFAST model there is

Mode  |  % Critical damping  |  % Log decrement
------- | ---------------------- | --------------------
1st flap   |  3.0 |  18.85
1st edge  | 3.0 |   18.85
2nd flap  | 8.4 | 52.78

and it looks rather high.

For comparison, in the NREL 5 MW the critical damping for all modes is set to 0.477465%, which corresponds to 3% log decrement.

Best regards,
Riccardo Riva

**Comment by ptrbortolotti** [comment]
Hi Riccardo,
thank you for spotting the bug. This was an oversight on our side. I tried to go back and see where these numbers came from, and I couldn't find the source of the error. I have now fixed them in the develop branch, which will soon be merged to master. 
Thanks again and best regards to CPH.
I close the issue.
Pietro
