### ISSUE TITLE
Looking for 32-bit DISCON_IEA_offshore.dll

### ISSUE THREAD

**Issue by wonny0503** [IEAWindTask37/IEA-10.0-198-RWT#29]
Dear IEA_10.0-198-RWT Community

I tried to run IEA-10.0-198-RWT-offshore simulation by DNV Bladed(v.4.10) and got error message.

***ERROR: Windows Error 193: either the dll is not a valid Win32 application, or a 32-bit process is trying to call a 64-bit process when calling 'DISCON_IEA_offshore.dll'.

I guess this problem is caused by DISCON_IEA_offshore.dll built by 64-bit but Bladed can read only 32-bit application.

Is there the newest version of .dll file and .IN file based on ROSCO 2.6.0 and 32-bit?

If not, Would you please guide me how to build those files based on 32-bit? 

I justed stepped into wind industry as student so i don't know how to get direction.

I really want to study but need more information from experts.

Best Regards,
wonny

**Comment by ptrbortolotti** [comment]
Hi wonny,
To recompile ROSCO on your specific platform, please follow the instructions available here https://github.com/NREL/ROSCO 
Note that I've just pushed new OpenFAST files compatible with OpenFAST 3.2 and ROSCO files compatible with ROSCO 2.6. 
Best regards,
Pietro Bortolotti

**Comment by wonny0503** [comment]
Dear ptrbortolotti

I really appreciated your quick respond and information.

And also, Updated files you pushed are really helpful and gave me the chance to study.

During I ran IEA-10.0-198-RWT-offshore simulation using OpenFAST, found that Monopile_SubDyn.dat and HydroDyn.dat are obsolete. 

I tried to format these files but it's beyond my capability.

Is there a plan for updating OpenFAST in offshore branch?

Best Regards,
wonny

**Comment by kashyap5794** [comment]
> Hi wonny, To recompile ROSCO on your specific platform, please follow the instructions available here https://github.com/NREL/ROSCO Note that I've just pushed new OpenFAST files compatible with OpenFAST 3.2 and ROSCO files compatible with ROSCO 2.6. Best regards, Pietro Bortolotti

Dear Sir, 

Will the given DLL work well with an older version of FAST? Like FAST v7. I need to use FAST v7 because of its capability to impose platform loads. In case it doesn't, how can I make it compatible?

Thanks
Subham
