### ISSUE TITLE
Non-flat power curve with operational data file (HAWCStab2)

### ISSUE THREAD

**Issue by jennirinker** [IEAWindTask37/IEA-10.0-198-RWT#30]
Hello!

It appears that the file data19.opt does not result in a flat power curve above rated (figure below). Maybe something changed with the design since the file was made?

I have attached here a newly generated .opt file based off of main which has a flat power curve above rated. @davidovitch I wasn't sure where to put it in the repo -- let me know if you want a MR.

Blue line: .pwr with current data19.opt. Red line: .pwr with attached .opt file.

![billede](https://user-images.githubusercontent.com/11503804/191455731-a3f99587-d7b6-4073-9c7a-bca4d1670f4c.png)

[steadystate.opt.txt](https://github.com/IEAWindTask37/IEA-10.0-198-RWT/files/9614710/steadystate.opt.txt)

EDIT: HAWC2S Version 2.16 revision dev0.ebaef36

**Comment by fzahle** [comment]
This difference could easily be due to updates in HAWCStab2, so let's get that merged, perhaps with a comment on the version of HS2 used.

**Comment by jennirinker** [comment]
Good point. I edited my comment to show with HAWC2S version I used (2.16), but my student using 2.15 found the same trend in the power curve. I have not, however, tried to recreate the power curve with 2.15 myself.
