### ISSUE TITLE
WindIO file has multiple anchors with id004

### ISSUE THREAD

**Issue by kenloen** [IEAWindTask37/IEA-10.0-198-RWT#33]
With WindIO description of the file has multiple definition of id004:
1. [line 47](https://github.com/IEAWindTask37/IEA-10.0-198-RWT/blob/master/yaml/IEA-10-198-RWT.yaml#L47)
2. [line 676](https://github.com/IEAWindTask37/IEA-10.0-198-RWT/blob/master/yaml/IEA-10-198-RWT.yaml#L676)

**Comment by fzahle** [comment]
The WindIO definition of the turbine needs a larger overhaul. The aero reference axis z-coordinate is also not correct, I now see. The blade is 96.2 m long (in radial (z) direction, not 96.755). There are also other inconsistencies in the `internal_structure_2d_fem` definition. We need to address these issues on our end.

**Comment by Stephen-cby** [comment]
Dear @fzahle,

I am interesting that whether this warning will influence the accurancy of the results.

Thanks for your reply.

**Comment by Stephen-cby** [comment]
I have run `wisdem` for IEA-10 IEA-15, respectively. It seems that the tower mass of 10 MW is larger than that of 15 MW. Specifically, 10 MW wind turbine has tower mass of 1103891.09043684 kg, while the tower mass of 15 MW wind turbine is 853463.23773881 kg.

I wonder whether these outcomes are correct or not, becaese the tower height of 10 MW is shorter than that of 15 MW

**Comment by ptrbortolotti** [comment]
None of the two towers has ever been subjected to a high fidelity design check and I would take both numbers with a gran of salt. I can only add that the tower of the IEA15 received more attention than the one from the IEA10

**Comment by Stephen-cby** [comment]
Hi, @ptrbortolotti and @fzahle.

Thanks for your replies. they help a lot. You have done a great job. Wind turbines of the IEA series are attracting more attention nowadays, as excellent reference models.

Considering your suggestions, I think it is more interesting to study 22 MW wind turbines, instead of 10 MW, at present.
