### ISSUE TITLE
ROSCO Issues

### ISSUE THREAD

**Issue by RBergua** [IEAWindTask37/IEA-10.0-198-RWT#34]
I'm trying to run the OpenFAST model (commit 9eafc6e) on Windows, but I'm having issues with the controller.

I'm using the model with OpenFAST v3.5.0 as indicated in the repo. But as soon as ServoDyn tries to read the controller parameters input file (*.IN), it crashes.
![image](https://github.com/IEAWindTask37/IEA-10.0-198-RWT/assets/33709140/0093abf8-be3a-4109-a5e8-a26544528d16)

The model works fine if I don't call ROSCO.

I'm wondering if I'm the only one experiencing theses issues?

**Comment by ptrbortolotti** [comment]
I've just tried things out, and they work on my Mac machine... That clearly points to a ROSCO error. Have you double checked that you are using v2.7.0? Have you maybe tried another version of ROSCO?

**Comment by RBergua** [comment]
I'm using the *.dll, *.IN, and *.dat provided in this repository. When trying to run the model, the *.IN doesn't work. My understanding is that the repo provides these files that are compatible with ROSCO v2.7.0 and the user should not make any changes. Please, let me know otherwise.

**Comment by ptrbortolotti** [comment]
I understand the confusion now. My apologies, that discon is outdated. Please compile/download ROSCO v2.7.0 yourself from here https://github.com/NREL/ROSCO/releases/tag/v2.7.0
I've now removed the outdated discon from this repo

**Comment by RBergua** [comment]
Thanks for the feedback, Pietro. I tried downloading the ROSCO v2.7.0 dll and now I move forward, but still crashing with the *.IN file. At least now it's just a variable missing in the line 8 of the *.IN file.
![image](https://github.com/IEAWindTask37/IEA-10.0-198-RWT/assets/33709140/2816ae91-17de-49bf-921d-e884d99c8892)

**Comment by RBergua** [comment]
I think I have a clear picture now. I was trying to run a *DISCON.IN from Dan Zalkind.

Summarizing, if you use the current *DISCON.IN from this repo (commit e04c259), you must use the ROSCO v2.7.0 from here: https://github.com/NREL/ROSCO/releases/tag/v2.7.0. The DLL available in the repo was older than ROSCO v2.7.0 and not compatible with the controller parameter input file.

The DISCON.txt that I attach here ([IEA-10.0-198-RWT_DISCON.txt] rename the file from *.txt to *.IN) from Dan is compatible with ROSCO v2.8.0. You should download ROSCO from here: 
https://github.com/IEAWindTask37/IEA-10.0-198-RWT/files/13663516/IEA-10.0-198-RWT_DISCON.txt

Hopefully this helps anyone that was struggling with the controller in the repo.

**Comment by ptrbortolotti** [comment]
thank you Roger!
