### ISSUE TITLE
OpenFAST wind ramp simulation: pitch oscillations and rated wind speed not matching design specs

### ISSUE THREAD

**Issue by Guiiem** [IEAWindTask37/IEA-10.0-198-RWT#38]
Hello!

I have tried a wind ramp simulation by setting `WindType` to `2` in the InflowFile and using the following time-series:

```
! Time     Wind    Wind    Vertical    Horiz.      Pwr.Law     Lin.Vert.   Gust     Upflow
!          Speed   Dir     Speed       Shear       Vert.Shr    Shear       Speed    Angle 
! (sec)    (m/s)   (Deg)   (m/s)                                            (m/s)   (deg)
0.00 3 0 0 0 0.2 0 0 8
1149.95 25 0 0 0 0.2 0 0 8
```

All the rest is left as it is in the last commit of master. I am using OpenFAST 3.5.0 and ROSCO 2.7.0.

After rated rotor speed is reached, there are some pitch oscillations. Even though they are small, the influence in power is quite large. Additionally, rated power is achieved at around 12 m/s, which is more than the 10.75 m/s documented in the Table 16 of the design report. I confirmed this in another steady simulation at 11 m/s with no upflow or shear, where I only got a generator power of around 9 MW. 

![windramp](https://github.com/user-attachments/assets/54a106a0-15cc-4b7d-883d-2a9f5b968a16)

Am I missing something?

Thank you!
Guillem

**Comment by ptrbortolotti** [comment]
Hello @Guiiem ,

I'm not too sure what's going on. I've just used the latest release of https://github.com/WISDEM/weis to retune ROSCO v2.9.0. I attach the DISCON. The gen power is 10MW, let me know if this seems to work 

[Archive.zip](https://github.com/user-attachments/files/17049533/Archive.zip)

**Comment by Guiiem** [comment]
Hi @ptrbortolotti , 

Thanks for the reply and all your work with these models! I have tried the new files with the wind ramp and the oscillations are still there:
![windramp_retuned](https://github.com/user-attachments/assets/f1ccba1c-6457-4125-9539-ef8ee657a1c3)

If pitch saturation is removed (`PS_Mode=0`) the rated speed matches better the expected power curve, but the oscillations are still there. If I test it in a wind step simulation (still no saturation), it looks quite stable, even though the behavior at the 11m/s jump is a bit strange:
![windstep](https://github.com/user-attachments/assets/b4aa33df-d4c3-4ba4-a0e9-6f418803861f)

By the way, the wind-ramp simulation of the IEA3.4MW cousin looks smooth and without oscillations, this difference is what made me curious what was going on here. 

1. What do you think about the pitch saturation? I can see that it changed in commit [059caf9](https://github.com/IEAWindTask37/IEA-10.0-198-RWT/commit/059caf9d2d7fefc3a3f41bd2983be5d8a48ce62d#diff-285c104a95dd5b39c5012b0ae4035aa947cd26e31fe6e519c20215a9294c9697). Before that, the pitch saturation used to start after 10 m/s, and now it starts around 9 m/s, below rated. 
2. What do think about the pitch oscillations? The controller looks stable in the wind-step and in single steady wind simulations, but I guess it is still not ideal that these oscillations appear in a wind ramp?

Thank you!
Guillem

**Comment by ptrbortolotti** [comment]
Thanks @Guillem. There could be different things going on, and I'm not entirely sure where to point my finger to. A few thoughts and ideas for debugging:
1) I suspect that switching the modeling of the structural dynamics from ElastoDyn to BeamDyn will get rid of those oscillations
2) I'd be curious to see what happens if you switch from UAMod=3 to UAMod=4 in AeroDyn15
3) We could try to improve the tuning of ROSCO by using the scripts available at https://rosco.readthedocs.io/en/latest/source/examples.html

Please let me know if these ideas help

**Comment by Guiiem** [comment]
Hello @ptrbortolotti, I have tried your suggestions and the oscillations are still there. I haven't exhaustively tried to retune the controller yet, but my first tests didn't help much. Actually I could not manage to replicate the original controller. Could you maybe share the yaml controller tuning file you used as input? It may also be useful to have it available in the repository. 

Thank you!

**Comment by ptrbortolotti** [comment]
hello, I'm sorry about this roadblock. I use https://github.com/WISDEM/WEIS to tune ROSCO, so I don't have a ROSCO input yaml to share. maybe @dzalkind has some tips

**Comment by dzalkind** [comment]
Hi @Guiiem, sorry for the delay.

I've added a ROSCO tuning yaml and updated DISCON to this PR: #40.

This IEA-10MW rotor has always been a bit odd in that it reaches rated speed well before it reaches rated torque/power.  When the oscillations occur near rated wind speed, both the torque and the pitch controller are trying to regulate the speed.  We generally try to avoid this using the set point smoothing logic in ROSCO.  By changing the gains of that loop, we can ensure that the pitch is only active once we reach rated power.

This is the expected response to a wind ramp:  
![image](https://github.com/user-attachments/assets/73d873a9-e997-4b5a-a4c6-e767512a4574)

**Comment by Guiiem** [comment]
Hi @dzalkind and @ptrbortolotti! Works for me too, the oscillations are gone. Thank you also for providing the controller yaml! 

If I remove the thrust peak shaving, the rated wind speed also coincides with the design report (which didn't have thrust shaving), so everything matches well now :)

Thanks a lot, appreciate your help!
