### ISSUE TITLE
IEA10MW Reference Wind Turbine Model (Elastodyn + Beamdyn) simulation FATAL ERROR

### ISSUE THREAD

**Issue by Derek03-pixel** [IEAWindTask37/IEA-10.0-198-RWT#39]
I want to run IEA10MW reference wind turbine model with and without Beamdyn. I'm using OpenFast-v3.5.0 and ROSCO-v2.7.0. The model has run successfully without Beamdyn. However, I couldn't run the model with `Beamdyn(CompElast=2)`. I tried to change DT = 0.01 to 0.0002 if it fixes, but the error message was not changed. 
Q1. What parameters should I change for the model to run successfully?
Best regards,
Dereje

`OpenFAST-v3.5.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 2021
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: May 17 2023
 - Time: 13:43:33
Execution Info:
 - Date: 10/09/2024
 - Time: 21:44:10+0800

OpenFAST input file heading:
    Generated with AeroElasticSE FAST driver

Running ElastoDyn.
Nodal outputs section of ElastoDyn input file not found or improperly formatted.
Running BeamDyn.
Nodal outputs section of BeamDyn input file not found or improperly formatted.
Running BeamDyn.
Nodal outputs section of BeamDyn input file not found or improperly formatted.
Running BeamDyn.
Nodal outputs section of BeamDyn input file not found or improperly formatted.
Running AeroDyn.
AD15 Nodal Outputs: Nodal output section of AeroDyn input file not found or improperly formatted.
Skipping nodal outputs.
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 5, blade 1)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 5, blade 2)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 3)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 5, blade 3)
Running InflowWind.

   Reading a 61x41 grid (300 m wide, 19 m to 219 m above ground) with a characteristic wind speed
   of 8 m/s. This full-field file was generated by TurbSim (from OpenFAST-v3.4.0) on 09-Oct-2024
   at 21:24:29.

   Processed 12000 time steps of 20-Hz grid-field data (period of 600 seconds).
Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows).
Using legacy Bladed DLL interface.

FAST_InitializeAll:InitModuleMappings:BD_2_AD_BladeMotion(1):MeshMapCreate:CreateMotionMap_L2_to_L
2:CreateMapping_ProjectToLine2:Node 30 does not project onto any line2 element. Closest distance
is 0.51937 m.
InitModuleMappings:AD_2_BD_BladeLoad(1):MeshMapCreate:CreateLoadMap_L2_to_L2:CreateMapping_Project
ToLine2:Found close value for node 91. (1.38448E-05 m)
CreateMapping_ProjectToLine2:Node 30 does not project onto any line2 element. Closest distance is
0.51937 m.
InitModuleMappings:BD_2_AD_BladeMotion(2):MeshMapCreate:CreateMotionMap_L2_to_L2:CreateMapping_Pro
jectToLine2:Node 30 does not project onto any line2 element. Closest distance is 0.51936 m.
InitModuleMappings:AD_2_BD_BladeLoad(2):MeshMapCreate:CreateLoadMap_L2_to_L2:CreateMapping_Project
ToLine2:Node 30 does not project onto any line2 element. Closest distance is 0.51936 m.
InitModuleMappings:BD_2_AD_BladeMotion(3):MeshMapCreate:CreateMotionMap_L2_to_L2:CreateMapping_Pro
jectToLine2:Node 30 does not project onto any line2 element. Closest distance i

 OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.`

**Comment by ptrbortolotti** [comment]
https://github.com/IEAWindTask37/IEA-10.0-198-RWT/tree/fix_beamdyn this fix will make BeamDyn run. Note however that I have not had the time to verify the model and in the windIO yaml file I can see layers that are not correctly defined, so I cannot run our 2D solver https://github.com/ptrbortolotti/SONATA. This 10MW model is growing outdated. If possible, I'd recommend jumping to newer models, such as the https://github.com/IEAWindTask37/IEA-22-280-RWT/tree/main

**Comment by Derek03-pixel** [comment]
I ran the IEA 10MW  reference wind turbine model, and it worked successfully. I appreciate your help. 
 Best regards,
 Dereje

**Comment by PaulKSmith** [comment]
Hello @Derek03-pixel ,
Which timestep size are you using ? The default '0.01' does not converge even with https://github.com/IEAWindTask37/IEA-10.0-198-RWT/tree/fix_beamdyn . Decreasing it 10 times makes it very slow. Could you share your experience ?

Regards,

**Comment by Derek03-pixel** [comment]
Hi @PaulKSmith ,
Thank you for reaching out.
In my experience, the model works well with a timestep size of 0.001. Using the default timestep of 0.01 does indeed lead to convergence issues, especially when working with Beamdyn. Although reducing the timestep to 0.001 increases the simulation time, it ensures stability and accurate results.

Best regards,
Dereje Haile

**Comment by PaulKSmith** [comment]
@Derek03-pixel , Thanks for confirming!
